[zsh] Tweak alias avenv to look for either .env or venv

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -23,7 +23,9 @@ function wincp {
 function src_if_exists {
 	if [ -e "$1" ]; then
 		source "$1"
+        return 0
 	fi
+    return 1
 }
 
 function src_if_os {
@@ -137,7 +139,8 @@ alias tmuxa="tmux new-session -A -s main"
 alias tmuxs="tmux new-session -A -s"
 alias devd="vim \$(devdiary.py --add --latest)"
 alias devdsum="devdiary.py --summarize | less"
-alias avenv="source venv/bin/activate"
+alias avenv='src_if_exists .env/bin/activate || src_if_exists .env/bin/activate || echo "Unable to find venv or .env"'
+alias venv-setup="virtualenv -p python3 .env"
 alias ungrab_mouse="setxkbmap -option grab:break_actions && xdotool key XF86Ungrab"
 
 src_if_exists "$HOME/.aliases"
